### PR TITLE
feat: #2 - Add graphviz plugin, update other plugins, add test action

### PR DESCRIPTION
**Pull request by grzesuav**

### CODE REVIEW

**Comment by grzesuav** [comment]
example job result https://github.com/grzesuav/mdbook-docker-image/actions/runs/614892804

**Comment by Michael-F-Bryan** [comment]
This is awesome!

I'll try to build it locally, and merge merge this PR once it succeeds.

**Comment by grzesuav** [comment]
> This is awesome!
> 
> I'll try to build it locally, and merge merge this PR once it succeeds.

sure, thank you. After merge to master each up-to-date branch/fork should have attached test job to verify docker build

**Comment by Michael-F-Bryan** [comment]
New images have been uploaded :partying_face: 

https://hub.docker.com/r/michaelfbryan/mdbook-docker-image/tags?page=1&ordering=last_updated

**Pull request merged**
